version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:3000"
    external_links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./.cms/data:/etc/mongo
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL:"mongodb://mongo:27017"
    depends_on:
      - mongo
