version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - /.cms:/etc/mongo
    ports:
      - "27017:27017"
  mongo-express:
    container_name: my-mongo-express
    image: mongo-express
    ports:
      - "8081:80801"
